apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels: # service will have this label
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: # service will forward request to pods with label key=value
    {{- include "deployment.selector" . | nindent 4 }}
  ports:
    - name: http        # referenced by ingress
      port: 5678        # service port number
      targetPort: http  # looks up the named port in selected pods
